$(window).scroll(function(){100<=$(window).scrollTop()?$(".header").addClass("bgchange"):$(".header").removeClass("bgchange")});function toggle_visibility(a){a=document.getElementById(a);a.style.display="block"==a.style.display?"none":"block"}$(".turn").click(function(){$(".address").slideUp("slow")});jQuery(document).ready(function(a){a(".counter").counterUp({delay:10,time:1E3})});
(function(a){function c(){e=!1;for(var b=0;b<d.length;b++){var f=a(d[b]).filter(function(){return a(this).is(":appeared")});f.trigger("appear",[f]);if(k){var c=k.not(f);c.trigger("disappear",[c])}k=f}}var d=[],b=!1,e=!1,h={interval:250,force_process:!1},g=a(window),k;a.expr[":"].appeared=function(b){b=a(b);if(!b.is(":visible"))return!1;var e=g.scrollLeft(),d=g.scrollTop(),c=b.offset(),h=c.left,c=c.top;return c+b.height()>=d&&c-(b.data("appear-top-offset")||0)<=d+g.height()&&h+b.width()>=e&&h-(b.data("appear-left-offset")||
0)<=e+g.width()?!0:!1};a.fn.extend({appear:function(g){var f=a.extend({},h,g||{});g=this.selector||this;if(!b){var k=function(){e||(e=!0,setTimeout(c,f.interval))};a(window).scroll(k).resize(k);b=!0}f.force_process&&setTimeout(c,f.interval);d.push(g);return a(g)}});a.extend({force_appear:function(){return b?(c(),!0):!1}})})(jQuery);
(function(a){function c(e){function c(){e?p.removeData(e):l&&delete d[l]}function g(){f.id=setTimeout(function(){f.fn()},q)}var k=this,p,f={},s=e?a.fn:a,m=arguments,r=4,l=m[1],q=m[2],n=m[3];"string"!==typeof l&&(r--,l=e=0,q=m[1],n=m[2]);e?(p=k.eq(0),p.data(e,f=p.data(e)||{})):l&&(f=d[l]||(d[l]={}));f.id&&clearTimeout(f.id);delete f.id;if(n)f.fn=function(a){"string"===typeof n&&(n=s[n]);!0!==n.apply(k,b.call(m,r))||a?c():g()},g();else{if(f.fn)return void 0===q?c():f.fn(!1===q),!0;c()}}"$:nomunge";
var d={},b=Array.prototype.slice;a.doTimeout=function(){return c.apply(window,[0].concat(b.call(arguments)))};a.fn.doTimeout=function(){var a=b.call(arguments),d=c.apply(this,["doTimeout"+a[0]].concat(a));return"number"===typeof a[0]||"number"===typeof a[1]?this:d}})(jQuery);$(".animatedParent").appear();
$(".animatedClick").click(function(){var a=$(this).attr("data-target");if(void 0!=$(this).attr("data-sequence")){var c=$("."+a+":first").attr("data-id"),d=$("."+a+":last").attr("data-id"),b=c;$("."+a+"[data-id="+b+"]").hasClass("go")?($("."+a+"[data-id="+b+"]").addClass("goAway"),$("."+a+"[data-id="+b+"]").removeClass("go")):($("."+a+"[data-id="+b+"]").addClass("go"),$("."+a+"[data-id="+b+"]").removeClass("goAway"));b++;delay=Number($(this).attr("data-sequence"));$.doTimeout(delay,function(){console.log(d);
$("."+a+"[data-id="+b+"]").hasClass("go")?($("."+a+"[data-id="+b+"]").addClass("goAway"),$("."+a+"[data-id="+b+"]").removeClass("go")):($("."+a+"[data-id="+b+"]").addClass("go"),$("."+a+"[data-id="+b+"]").removeClass("goAway"));++b;if(b<=d)return!0})}else $("."+a).hasClass("go")?($("."+a).addClass("goAway"),$("."+a).removeClass("go")):($("."+a).addClass("go"),$("."+a).removeClass("goAway"))});
$(document.body).on("appear",".animatedParent",function(a,c){var d=$(this).find(".animated"),b=$(this);if(void 0!=b.attr("data-sequence")){var e=$(this).find(".animated:first").attr("data-id"),h=$(this).find(".animated:last").attr("data-id");$(b).find(".animated[data-id="+e+"]").addClass("go");e++;delay=Number(b.attr("data-sequence"));$.doTimeout(delay,function(){$(b).find(".animated[data-id="+e+"]").addClass("go");++e;if(e<=h)return!0})}else d.addClass("go")});
$(document.body).on("disappear",".animatedParent",function(a,c){$(this).hasClass("animateOnce")||$(this).find(".animated").removeClass("go")});$(window).load(function(){$.force_appear()});(function(a){a.fn.parallax=function(c){var d=a(window).height(),b=a.extend({speed:0.15},c);return this.each(function(){var c=a(this);a(document).scroll(function(){var h=a(window).scrollTop(),g=c.offset().top,k=c.outerHeight();g+k<=h||g>=h+d||(h=Math.round((g-h)*b.speed),c.css("background-position","center "+h+"px"))})})}})(jQuery);
$(".parallax-section").parallax({speed:0.2});
(function(){var a,c=function(){var c=window.innerHeight||document.documentElement.clientHeight;jQuery.each(a.cssRules||a.rules,function(a,e){var h=e.selectorText.toLowerCase().replace(".win-","").replace("-h","H");e.style[h]=c+"px"})};(function(){var d=jQuery("<style>").appendTo("head");a=d.prop("sheet")||d.prop("styleSheet");d=function(b,c,d){a.insertRule?a.insertRule(b+"{"+c+"}",d):a.addRule(b,c,d)};d(".win-min-height","min-height:0");d(".win-height","height:auto");d(".win-max-height","max-height:100%");
c()})();jQuery(window).on("resize orientationchange",c)})();$("a#play").click(function(){$(".video_holder").animate({width:"100%",height:"100%"});$(".video_holder").css("border-radius","0");$(".embed-container").css("padding-bottom","56.25%");$("span.play-btn").hide()});(function(a){var c=a(window),d=a(".ts");c.resize(function(){d.addClass("m-scooch");if(480<c.width())return d.removeClass("m-scooch")}).trigger("resize")})(jQuery);
$(window).resize(function(){var a=$(window).width();320<=a&&768>=a?($("#block01g").removeClass("background01").addClass("background02"),$(".searchfeild").removeClass("color02").addClass("color01")):768<=a&&2E3>=a&&($("#block01g").removeClass("background02").addClass("background01"),$(".searchfeild").removeClass("color01").addClass("color02"))}).resize();$(window).resize(function(){var a=$(window).width();320<=a&&480>=a?$("#ourprojects").removeClass("carousel-inner"):481<=a&&2E3>=a&&$("#ourprojects").addClass("carousel-inner")}).resize();
$(window).load(function(){$(".demo").customScrollbar();$("#fixed-thumb-size-demo").customScrollbar({fixedThumbHeight:50,fixedThumbWidth:60})});$(function(){$('[data-toggle="popover"]').popover()});$(function(){$('[data-toggle="tooltip"]').tooltip()});$(".my_tooltip").tooltip({placement:"bottom",html:!0});
jQuery(document).ready(function(a){var c=a("#gallery-1, #gallery-2").royalSlider({addActiveClass:!0,arrowsNav:!0,controlNavigation:"none",autoScaleSlider:!0,autoScaleSliderWidth:960,autoScaleSliderHeight:340,loop:!0,fadeinLoadedSlide:!1,globalCaption:!0,keyboardNavEnabled:!0,globalCaptionInside:!1,visibleNearby:{enabled:!0,centerArea:0.5,center:!0,breakpoint:650,breakpointCenterArea:0.64,navigateByCenterClick:!0}}).data("royalSlider");a(".slide4link").click(function(a){c.goTo(4);return!1})});$(".m-scooch").scooch();
