window.Modernizr=function(d,h,k){function q(f,b){for(var g in f){var n=f[g];if(!~(""+n).indexOf("-")&&E[n]!==k)return"pfx"==b?n:!0}return!1}function m(f,b,g){var n=f.charAt(0).toUpperCase()+f.slice(1),h=(f+" "+F.join(n+" ")+n).split(" ");if("string"===typeof b||"undefined"===typeof b)b=q(h,b);else a:{h=(f+" "+D.join(n+" ")+n).split(" "),f=h;for(var d in f)if(n=b[f[d]],n!==k){b=!1===g?f[d]:"function"===typeof n?n.bind(g||b):n;break a}b=!1}return b}var g={},B=h.documentElement,p=h.createElement("modernizr"),
E=p.style,F=["Webkit","Moz","O","ms"],D=["webkit","moz","o","ms"],p={};d=[];var s=d.slice,w,x={}.hasOwnProperty,y;"undefined"===typeof x||"undefined"===typeof x.call?y=function(f,b){return b in f&&"undefined"===typeof f.constructor.prototype[b]}:y=function(f,b){return x.call(f,b)};Function.prototype.bind||(Function.prototype.bind=function(f){var b=this;if("function"!=typeof b)throw new TypeError;var g=s.call(arguments,1),h=function(){if(this instanceof h){var d=function(){};d.prototype=b.prototype;
var d=new d,k=b.apply(d,g.concat(s.call(arguments)));return Object(k)===k?k:d}return b.apply(f,g.concat(s.call(arguments)))};return h});p.csstransitions=function(){return m("transition")};for(var z in p)y(p,z)&&(w=z.toLowerCase(),g[w]=p[z](),d.push((g[w]?"":"no-")+w));g.addTest=function(f,b){if("object"==typeof f)for(var h in f)y(f,h)&&g.addTest(h,f[h]);else{f=f.toLowerCase();if(g[f]!==k)return g;b="function"==typeof b?b():b;B.className+=" "+(b?"":"no-")+f;g[f]=b}return g};E.cssText="";return p=null,
function(f,b){function h(){var a=A.elements;return"string"==typeof a?a.split(" "):a}function g(J){var c=v[J[t]];return c||(c={},a++,J[t]=a,v[a]=c),c}function d(a,c,e){c||(c=b);if(C)return c.createElement(a);e||(e=g(c));var l;return e.cache[a]?l=e.cache[a].cloneNode():s.test(a)?l=(e.cache[a]=e.createElem(a)).cloneNode():l=e.createElem(a),!l.canHaveChildren||u.test(a)||l.tagUrn?l:e.frag.appendChild(l)}function k(a,c){c.cache||(c.cache={},c.createElem=a.createElement,c.createFrag=a.createDocumentFragment,
c.frag=c.createFrag());a.createElement=function(e){return A.shivMethods?d(e,a,c):c.createElem(e)};a.createDocumentFragment=Function("h,f","return function(){var n=f.cloneNode(),c=n.createElement;h.shivMethods&&("+h().join().replace(/[\w\-]+/g,function(a){return c.createElem(a),c.frag.createElement(a),'c("'+a+'")'})+");return n}")(A,c.frag)}function p(a){a||(a=b);var c=g(a);if(A.shivCSS&&!q&&!c.hasCSS){var e,l=a;e=l.createElement("p");l=l.getElementsByTagName("head")[0]||l.documentElement;e=(e.innerHTML=
"x<style>article,aside,dialog,figcaption,figure,footer,header,hgroup,main,nav,section{display:block}mark{background:#FF0;color:#000}template{display:none}</style>",l.insertBefore(e.lastChild,l.firstChild));c.hasCSS=!!e}return C||k(a,c),a}var m=f.html5||{},u=/^<|^(?:button|map|select|textarea|object|iframe|option|optgroup)$/i,s=/^(?:a|b|code|div|fieldset|h1|h2|h3|h4|h5|h6|i|label|li|ol|p|q|span|strong|style|table|tbody|td|th|tr|ul)$/i,q,t="_html5shiv",a=0,v={},C;(function(){try{var a=b.createElement("a");
a.innerHTML="<xyz></xyz>";q="hidden"in a;var c;if(!(c=1==a.childNodes.length)){b.createElement("a");var e=b.createDocumentFragment();c="undefined"==typeof e.cloneNode||"undefined"==typeof e.createDocumentFragment||"undefined"==typeof e.createElement}C=c}catch(l){C=q=!0}})();var A={elements:m.elements||"abbr article aside audio bdi canvas data datalist details dialog figcaption figure footer header hgroup main mark meter nav output progress section summary template time video",version:"3.7.0",shivCSS:!1!==
m.shivCSS,supportsUnknownElements:C,shivMethods:!1!==m.shivMethods,type:"default",shivDocument:p,createElement:d,createDocumentFragment:function(a,c){a||(a=b);if(C)return a.createDocumentFragment();c=c||g(a);for(var e=c.frag.cloneNode(),l=0,f=h(),v=f.length;l<v;l++)e.createElement(f[l]);return e}};f.html5=A;p(b)}(this,h),g._version="2.7.1",g._domPrefixes=D,g._cssomPrefixes=F,g.testProp=function(f){return q([f])},g.testAllProps=m,g.prefixed=function(f,b,h){return b?m(f,b,h):m(f,"pfx")},B.className=
B.className.replace(/(^|\s)no-js(\s|$)/,"$1$2")+(" js "+d.join(" ")),g}(this,this.document);
(function(d,h,k){function q(a){return"[object Function]"==y.call(a)}function m(a){return"string"==typeof a}function g(){}function B(a){return!a||"loaded"==a||"complete"==a||"uninitialized"==a}function p(){var a=z.shift();f=1;a?a.t?w(function(){("c"==a.t?t.injectCss:t.injectJs)(a.s,0,a.a,a.x,a.e,1)},0):(a(),p()):f=0}function E(a,b,g,d,k,c,e){function l(c){if(!N&&B(r.readyState)&&(q.r=N=1,!f&&p(),r.onload=r.onreadystatechange=null,c)){"img"!=a&&w(function(){n.removeChild(r)},50);for(var e in u[b])u[b].hasOwnProperty(e)&&
u[b][e].onload()}}e=e||t.errorTimeout;var r=h.createElement(a),N=0,m=0,q={t:g,s:b,e:k,a:c,x:e};1===u[b]&&(m=1,u[b]=[]);"object"==a?r.data=b:(r.src=b,r.type=a);r.width=r.height="0";r.onerror=r.onload=r.onreadystatechange=function(){l.call(this,m)};z.splice(d,0,q);"img"!=a&&(m||2===u[b]?(n.insertBefore(r,H?null:x),w(l,e)):u[b].push(r))}function F(a,b,h,g,d){return f=0,b=b||"j",m(a)?E("c"==b?O:I,a,b,this.i++,h,g,d):(z.splice(this.i++,0,a),1==z.length&&p()),this}function D(){var a=t;return a.loader={load:F,
i:0},a}var s=h.documentElement,w=d.setTimeout,x=h.getElementsByTagName("script")[0],y={}.toString,z=[],f=0,b="MozAppearance"in s.style,H=b&&!!h.createRange().compareNode,n=H?s:x.parentNode,s=d.opera&&"[object Opera]"==y.call(d.opera),s=!!h.attachEvent&&!s,I=b?"object":s?"script":"img",O=s?"script":I,L=Array.isArray||function(a){return"[object Array]"==y.call(a)},G=[],u={},K={timeout:function(a,b){return b.length&&(a.timeout=b[0]),a}},M,t;t=function(a){function b(a){a=a.split("!");var e=G.length,c=
a.pop(),f=a.length,c={url:c,origUrl:c,prefixes:a},h,g,d;for(g=0;g<f;g++)d=a[g].split("="),(h=K[d.shift()])&&(c=h(c,d));for(g=0;g<e;g++)c=G[g](c);return c}function f(a,c,e,g,h){var d=b(a),m=d.autoCallback;d.url.split(".").pop().split("?").shift();d.bypass||(c&&(c=q(c)?c:c[a]||c[g]||c[a.split("/").pop().split("?")[0]]),d.instead?d.instead(a,c,e,g,h):(u[d.url]?d.noexec=!0:u[d.url]=1,e.load(d.url,d.forceCSS||!d.forceJS&&"css"==d.url.split(".").pop().split("?").shift()?"c":k,d.noexec,d.attrs,d.timeout),
(q(c)||q(m))&&e.load(function(){D();c&&c(d.origUrl,h,g);m&&m(d.origUrl,h,g);u[d.url]=2})))}function h(a,c){function b(a,e){if(a)if(m(a))e||(k=function(){var a=[].slice.call(arguments);p.apply(this,a);n()}),f(a,k,c,0,d);else{if(Object(a)===a)for(v in A=function(){var c=0,b;for(b in a)a.hasOwnProperty(b)&&c++;return c}(),a)a.hasOwnProperty(v)&&(!e&&!--A&&(q(k)?k=function(){var a=[].slice.call(arguments);p.apply(this,a);n()}:k[v]=function(a){return function(){var c=[].slice.call(arguments);a&&a.apply(this,
c);n()}}(p[v])),f(a[v],k,c,v,d))}else!e&&n()}var d=!!a.test,e=a.load||a.both,k=a.callback||g,p=k,n=a.complete||g,A,v;b(d?a.yep:a.nope,!!e);e&&b(e)}var d,c,e=this.yepnope.loader;if(m(a))f(a,0,e,0);else if(L(a))for(d=0;d<a.length;d++)c=a[d],m(c)?f(c,0,e,0):L(c)?t(c):Object(c)===c&&h(c,e);else Object(a)===a&&h(a,e)};t.addPrefix=function(a,b){K[a]=b};t.addFilter=function(a){G.push(a)};t.errorTimeout=1E4;null==h.readyState&&h.addEventListener&&(h.readyState="loading",h.addEventListener("DOMContentLoaded",
M=function(){h.removeEventListener("DOMContentLoaded",M,0);h.readyState="complete"},0));d.yepnope=D();d.yepnope.executeStack=p;d.yepnope.injectJs=function(a,b,d,f,k,c){var e=h.createElement("script"),l,m;f=f||t.errorTimeout;e.src=a;for(m in d)e.setAttribute(m,d[m]);b=c?p:b||g;e.onreadystatechange=e.onload=function(){!l&&B(e.readyState)&&(l=1,b(),e.onload=e.onreadystatechange=null)};w(function(){l||(l=1,b(1))},f);k?e.onload():x.parentNode.insertBefore(e,x)};d.yepnope.injectCss=function(a,b,d,f,k,c){f=
h.createElement("link");var e;b=c?p:b||g;f.href=a;f.rel="stylesheet";f.type="text/css";for(e in d)f.setAttribute(e,d[e]);k||(x.parentNode.insertBefore(f,x),w(b,0))}})(this,document);Modernizr.load=function(){yepnope.apply(window,[].slice.call(arguments,0))};
(function(){function d(){if(classie.has(k,"open")){classie.remove(k,"open");classie.add(k,"close");var d=function(g){if(support.transitions){if("visibility"!==g.propertyName)return;this.removeEventListener(transEndEventName,d)}classie.remove(k,"close")};support.transitions?k.addEventListener(transEndEventName,d):d()}else classie.has(k,"close")||classie.add(k,"open")}var h=document.getElementById("trigger-overlay"),k=document.querySelector("div.overlay"),q=null==k?void 0:k.querySelector("button.overlay-close");
transEndEventNames={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",OTransition:"oTransitionEnd",msTransition:"MSTransitionEnd",transition:"transitionend"};transEndEventName=transEndEventNames[Modernizr.prefixed("transition")];support={transitions:Modernizr.csstransitions};null!=h&&h.addEventListener("click",d);null!=q&&q.addEventListener("click",d)})();
