(function(k){"function"===typeof define&&define.amd?define(["$"],k):k(window.Mobify&&window.Mobify.$||window.Zepto||window.jQuery);$(".m-scooch").scooch()})(function(k){var w=function(f){var c={},k=navigator.userAgent,h=f.support=f.support||{};f.extend(f.support,{touch:"ontouchend"in document});c.events=h.touch?{down:"touchstart",move:"touchmove",up:"touchend"}:{down:"mousedown",move:"mousemove",up:"mouseup"};c.getCursorPosition=h.touch?function(a){a=a.originalEvent||a;return{x:a.touches[0].clientX,
y:a.touches[0].clientY}}:function(a){return{x:a.clientX,y:a.clientY}};c.getProperty=function(a){for(var g=["Webkit","Moz","O","ms",""],b=document.createElement("div").style,c=0;c<g.length;++c)if(void 0!==b[g[c]+a])return g[c]+a};f.extend(h,{transform:!!c.getProperty("Transform"),transform3d:!(!(window.WebKitCSSMatrix&&"m11"in new WebKitCSSMatrix)||/android\s+[1-2]/i.test(k))});var e=c.getProperty("Transform");c.translateX=h.transform3d?function(a,g){"number"==typeof g&&(g+="px");a.style[e]="translate3d("+
g+",0,0)"}:h.transform?function(a,g){"number"==typeof g&&(g+="px");a.style[e]="translate("+g+",0)"}:function(a,g){"number"==typeof g&&(g+="px");a.style.left=g};c.getProperty("Transition");var b=c.getProperty("TransitionDuration");c.setTransitions=function(a,g){a.style[b]=g?"":"0s"};c.requestAnimationFrame=function(){var a=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,
1E3/60)};return function(){a.apply(window,arguments)}}();return c}(k),x=function(f,c){var k={dragRadius:10,moveRadius:20,animate:!0,autoHideArrows:!1,classPrefix:"m-",classNames:{outer:"scooch",inner:"scooch-inner",item:"item",center:"center",touch:"has-touch",dragging:"dragging",active:"active",inactive:"inactive",fluid:"fluid"}},h=f.support,e=function(b,a){this.setOptions(a);this.initElements(b);this.initOffsets();this.initAnimation();this.bind();this._updateCallbacks=[]};e.defaults=k;e.prototype.setOptions=
function(b){var a=this.options||f.extend({},k,b);a.classNames=f.extend({},a.classNames,b.classNames||{});this.options=a};e.prototype.initElements=function(b){this._index=1;this.element=b;this.$element=f(b);this.$inner=this.$element.find("."+this._getClass("inner"));this.$items=this.$inner.children();this.$start=this.$items.eq(0);this.$sec=this.$items.eq(1);this.$current=this.$items.eq(this._index-1);this._length=this.$items.length;this._alignment=this.$element.hasClass(this._getClass("center"))?0.5:
0;this._isFluid=this.$element.hasClass(this._getClass("fluid"))};e.prototype.initOffsets=function(){this._offsetDrag=0};e.prototype.initAnimation=function(){this._needsUpdate=this.dragging=this.animating=!1;this._enableAnimation()};e.prototype._getClass=function(b){return this.options.classPrefix+this.options.classNames[b]};e.prototype._enableAnimation=function(){this.animating||(c.setTransitions(this.$inner[0],!0),this.$inner.removeClass(this._getClass("dragging")),this.animating=!0)};e.prototype._disableAnimation=
function(){this.animating&&(c.setTransitions(this.$inner[0],!1),this.$inner.addClass(this._getClass("dragging")),this.animating=!1)};e.prototype.refresh=function(){this.$items=this.$inner.children("."+this._getClass("item"));this.$start=this.$items.eq(0);this.$sec=this.$items.eq(1);this._length=this.$items.length;this.update()};e.prototype.update=function(b){"undefined"!=typeof b&&this._updateCallbacks.push(b);if(!this._needsUpdate){this._needsUpdate=!0;var a=this;c.requestAnimationFrame(function(){a._update();
setTimeout(function(){for(var b=0,c=a._updateCallbacks.length;b<c;b++)a._updateCallbacks[b].call(a);a._updateCallbacks=[]},10)})}};e.prototype._update=function(){if(this._needsUpdate){var b=this.$current,a=this.$start,b=b.prop("offsetLeft")+b.prop("clientWidth")*this._alignment,a=a.prop("offsetLeft")+a.prop("clientWidth")*this._alignment,a=Math.round(-(b-a)+this._offsetDrag);c.translateX(this.$inner[0],a);this._needsUpdate=!1}};e.prototype.bind=function(){function b(b){g&&(g=!1,d._enableAnimation(),
!e&&a(l)>s.moveRadius?0<l?d.next():d.prev():(d._offsetDrag=0,d.update()))}var a=Math.abs,g=!1,e=!1,k=this.options.dragRadius,r,l,m,p,d=this,q=this.$element,n=this.$inner,s=this.options,t=!1,u=!1,v=f(window).width();n.on(c.events.down+".scooch",function(a){h.touch||a.preventDefault();g=!0;e=!1;r=c.getCursorPosition(a);m=l=0;p=!1;d._disableAnimation();t=1==d._index;u=d._index==d._length}).on(c.events.move+".scooch",function(b){if(g&&!e){var f=c.getCursorPosition(b),h=d.$element.width();l=r.x-f.x;m=
r.y-f.y;p||a(l)>a(m)&&a(l)>k?(p=!0,b.preventDefault(),t&&0>l?l=l*-h/(l-h):u&&0<l&&(l=l*h/(l+h)),d._offsetDrag=-l,d.update()):a(m)>a(l)&&a(m)>k&&(e=!0)}}).on(c.events.up+".scooch",b).on("click.scooch",function(a){p&&a.preventDefault()}).on("mouseout.scooch",b);q.on("click","[data-m-slide]",function(a){a.preventDefault();a=f(this).attr("data-m-slide");var b=parseInt(a,10);if(isNaN(b))d[a]();else d.move(b)});q.on("afterSlide",function(a,b,c){d.$items.eq(b-1).removeClass(d._getClass("active"));d.$items.eq(c-
1).addClass(d._getClass("active"));d.$element.find("[data-m-slide='"+b+"']").removeClass(d._getClass("active"));d.$element.find("[data-m-slide='"+c+"']").addClass(d._getClass("active"));s.autoHideArrows&&(1===c?(d.$element.find("[data-m-slide=prev]").addClass(d._getClass("inactive")),d.$element.find("[data-m-slide=next]").removeClass(d._getClass("inactive"))):c===d._length?(d.$element.find("[data-m-slide=next]").addClass(d._getClass("inactive")),d.$element.find("[data-m-slide=prev]").removeClass(d._getClass("inactive"))):
(d.$element.find("[data-m-slide=prev]").removeClass(d._getClass("inactive")),d.$element.find("[data-m-slide=next]").removeClass(d._getClass("inactive"))))});f(window).on("resize orientationchange",function(a){v!=f(window).width()&&(d._disableAnimation(),v=f(window).width(),d.update())});q.trigger("beforeSlide",[1,1]);q.trigger("afterSlide",[1,1]);d.update()};e.prototype.unbind=function(){this.$inner.off()};e.prototype.destroy=function(){this.unbind();this.$element.trigger("destroy");this.$element.remove();
this.$current=this.$start=this.$inner=this.$element=null};e.prototype.move=function(b,a){var c=this.$element,e=this.$items,k=this._length,h=this._index;a=f.extend({},this.options,a);1>b?b=1:b>this._length&&(b=k);a.animate?this._enableAnimation():this._disableAnimation();c.trigger("beforeSlide",[h,b]);this.$current=e.eq(b-1);this._offsetDrag=0;this._index=b;a.animate?this.update():this.update(function(){this._enableAnimation()});c.trigger("afterSlide",[h,b])};e.prototype.next=function(){this.move(this._index+
1)};e.prototype.prev=function(){this.move(this._index-1)};return e}(k,w);k.fn.scooch=function(f,c){var n=k.extend({},k.fn.scooch.defaults);"object"==typeof f&&(k.extend(n,f,!0),f=c=null);c=Array.prototype.slice.apply(arguments);this.each(function(){k(this);var h=this._scooch;h||(h=new x(this,n));f&&(h[f].apply(h,c.slice(1)),"destroy"===f&&(h=null));this._scooch=h});return this};k.fn.scooch.defaults={}});
